/**
 * Environment access, validated at point of use rather than at import time.
 *
 * Import-time validation would be tidier, but this module is reached from Next.js
 * middleware (edge runtime) as well as from Server Actions, and a throw during
 * module evaluation in middleware takes down every route including /login — which
 * is exactly where you'd want to see the error message. Lazy getters that throw a
 * specific message at the call site are debuggable; a blank 500 on every route is not.
 */

function required(name: string): string {
  const value = process.env[name];
  if (!value || value.trim() === '') {
    throw new Error(
      `Missing required environment variable ${name}. See .env.example and docs/DEPLOYMENT.md.`,
    );
  }
  return value;
}

/**
 * The argon2id hash of the household passphrase — never the passphrase itself.
 * Generated by `npm run passphrase:hash` and set at deploy time.
 */
export function passphraseHash(): string {
  return required('APP_PASSPHRASE_HASH');
}

/**
 * HMAC key for session cookie signatures. Rotating it invalidates every live
 * session, which is the intended "log everyone out" lever.
 */
export function sessionSecret(): string {
  const secret = required('SESSION_SECRET');
  if (secret.length < 32) {
    throw new Error(
      'SESSION_SECRET must be at least 32 characters. Generate one with: openssl rand -base64 48',
    );
  }
  return secret;
}

export function databaseUrl(): string {
  return required('DATABASE_URL');
}

/**
 * Whether to set `Secure` on the session cookie.
 *
 * This cannot be inferred from the incoming request. Under `tailscale serve` the
 * app sees plain HTTP on localhost while the browser is on HTTPS, so sniffing the
 * protocol would wrongly drop `Secure` in exactly the deployment that has TLS.
 * Defaults to on in production (the Tailscale Serve deployment) and off otherwise
 * (plain-HTTP `npm run dev`, where a Secure cookie would be silently discarded by
 * the browser and login would appear to succeed then bounce straight back).
 */
export function cookieSecure(): boolean {
  const explicit = process.env.COOKIE_SECURE;
  if (explicit === 'true') return true;
  if (explicit === 'false') return false;
  return process.env.NODE_ENV === 'production';
}

/**
 * How stale the last successful backup may get before the in-app indicator
 * escalates to a warning. Default 48h, per the Phase 0 spec.
 */
export function backupStaleAfterHours(): number {
  const raw = process.env.BACKUP_STALE_AFTER_HOURS;
  if (!raw) return 48;
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 48;
}

/**
 * Alpha Vantage API key for live portfolio pricing.
 *
 * Deliberately nullable, unlike `passphraseHash`/`sessionSecret` above: the proposal's
 * provider abstraction must work with zero market-data provider connected (same posture
 * as Open Banking), not crash Account Detail or /portfolio if unset. Callers show
 * "Price unavailable" rather than a broken page.
 */
export function alphaVantageApiKey(): string | null {
  const value = process.env.ALPHA_VANTAGE_API_KEY;
  return value && value.trim() !== '' ? value : null;
}

/**
 * How stale a cached quote may get before a page load triggers a refetch. Default 24h —
 * ample for a household checking prices at most once a day, and keeps well inside Alpha
 * Vantage's free-tier daily rate limit for a small number of distinct tickers.
 */
export function quoteStaleAfterHours(): number {
  const raw = process.env.QUOTE_STALE_AFTER_HOURS;
  if (!raw) return 24;
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 24;
}

/**
 * Financial Modeling Prep API key for the stock analysis workbench's fundamentals
 * (Phase 4). Same nullable, gracefully-degrading shape as `alphaVantageApiKey` above —
 * the template `alphaVantageApiKey`'s own doc comment names for "any future provider
 * key": the workbench must work with zero fundamentals provider connected, not crash.
 */
export function fmpApiKey(): string | null {
  const value = process.env.FMP_API_KEY;
  return value && value.trim() !== '' ? value : null;
}

/**
 * How stale cached fundamentals may get before a lookup triggers a refetch. Default
 * 24h. Fundamentals (income statement, balance sheet, cash flow) change at most
 * quarterly in reality, so this could be much longer than a quote's staleness window —
 * kept the same as `quoteStaleAfterHours` for now since FMP's free tier (250 req/day)
 * is far less constrained than Alpha Vantage's (25 req/day), so there's no pressing
 * need to stretch it further yet.
 */
export function fundamentalsStaleAfterHours(): number {
  const raw = process.env.FUNDAMENTALS_STALE_AFTER_HOURS;
  if (!raw) return 24;
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 24;
}
