# syntax=docker/dockerfile:1

# Debian slim rather than Alpine: @node-rs/argon2 ships a prebuilt glibc binary
# (linux-x64-gnu), so argon2id needs no compiler here. On Alpine it would need the musl
# variant, and getting that wrong is exactly the "native deps complicate the Docker
# build" scenario PROPOSAL.md offers bcrypt as a fallback for. Avoided rather than
# worked around.
FROM node:22-bookworm-slim AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

# Fail the build loudly if the base image predates the Node WebCrypto HMAC timing fix
# (CVE-2026-21713, fixed 22.22.2) — the session token's forgery resistance
# (src/lib/auth/session.ts) depends on crypto.subtle.verify being constant-time. The
# `node:22-bookworm-slim` tag is floating and should already be patched by the time this
# builds, but a stale local layer cache is exactly the failure mode a silent floating
# tag can't catch — this makes it a build error instead.
RUN node -e " \
  const [maj, min, patch] = process.versions.node.split('.').map(Number); \
  const ok = maj > 22 || (maj === 22 && (min > 22 || (min === 22 && patch >= 2))); \
  if (!ok) { \
    console.error('Node ' + process.versions.node + ' predates 22.22.2 (CVE-2026-21713, WebCrypto HMAC timing fix). Update the base image.'); \
    process.exit(1); \
  } \
"


# --- Dependencies (all, including dev — needed to build and to run drizzle-kit) ------
FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci


# --- Build --------------------------------------------------------------------------
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# next.config.mjs sets output: 'standalone', which traces only the files the server
# actually needs.
RUN npm run build


# --- Migrator -----------------------------------------------------------------------
# Run with: docker compose run --rm migrate
#
# A separate image because drizzle-kit is a devDependency and has no business in the
# runtime image. deploy.sh invokes this between the pg_dump and bringing the app up, so
# migrations never run against an un-dumped database.
FROM base AS migrator
COPY --from=deps /app/node_modules ./node_modules
COPY package.json drizzle.config.ts ./
COPY drizzle ./drizzle
COPY src ./src
CMD ["npx", "drizzle-kit", "migrate"]


# --- Runtime ------------------------------------------------------------------------
FROM base AS runner
ENV NODE_ENV=production

# Non-root. The app writes nothing to its own filesystem — all state is in Postgres —
# so it does not need to own anything beyond what it reads.
RUN groupadd --system --gid 1001 nodejs \
  && useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
# 0.0.0.0 inside the container only. docker-compose.yml publishes the port on
# 127.0.0.1 exclusively, so nothing is reachable from the LAN — Tailscale is the only
# route in. See docs/DEPLOYMENT.md.
ENV HOSTNAME=0.0.0.0

# server.js is generated by Next's standalone output.
CMD ["node", "server.js"]
